version: "3"

services:
  cert_gen:
      image: paulczar/omgwtfssl
      volumes:
      - certs:/certs

  traefik:
      build: traefik/
      networks:
        - default
        - inside
      ports:
      - 80:80
      - 443:443
      - 8081:8081
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs

        

  templates:
      build : nginx-templates/
      container_name: "nginx-templates"
      ports:
        - "8090:80"
      networks: 
        - inside

  public-files:
      image: aikain/simplehttpserver:0.1
      container_name: "public-files"
      volumes:
        - files:/var/www/
      networks:
        - inside
      labels:
        - "traefik.frontend.rule=PathPrefixStrip:/files"
        - "traefik.backend=public-files"
        - "traefik.port=80"
        - "traefik.weight=10"
        - "traefik.enable=true"
  
  portainer:
      image: portainer/portainer
      container_name: "portainer-app"
      networks:
        - default
        - inside
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/portainer/data:/data
      command:  --host=unix:///var/run/docker.sock --logo "https://i.imgur.com/lwVlWt2.jpg" --templates "http://nginx-templates/templates.yml"

      labels:
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.backend=portainer"
        - "traefik.port=9000"
        - "traefik.weight=10"
        - "traefik.enable=true"
        - "traefik.passHostHeader=true"
        - "traefik.docker.network=default"
        - "traefik.frontend.entryPoints=http, https"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"
        # https://github.com/containous/traefik/issues/563#issuecomment-421360934
        - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
        - "traefik.frontend.redirect.replacement=$$1/portainer/"
        - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
  whoami:
      image: emilevauge/whoami
      labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      volumes:
      - certs:/certs
volumes:
  certs:
  files:
networks:
  inside:
    external: false